#!/usr/bin/with-contenv bash

if [ ! -d /media/movies ]; then
  echo "Creating /media/movies"
  mkdir -p /media/movies
  chown -R abc:abc /media/movies
fi

if [ ! -d /media/_torrent ]; then
  echo "Creating /media/_torrent"
  mkdir -p /media/_torrent
  chown -R abc:abc /media/_torrent
fi

if [ ! -d /config/radarr ]; then
  echo "Creating /config/radarr"
  mkdir -p /config/radarr
  chown -R abc:abc /config/radarr
fi
