#!/usr/bin/with-contenv bash

if [ ! -d /media/tvseries ]; then
  echo "Creating /media/tvseries"
  mkdir -p /media/tvseries
  chown -R abc:abc /media/tvseries
fi

if [ ! -d /media/_torrent ]; then
  echo "Creating /media/_torrent"
  mkdir -p /media/_torrent
  chown -R abc:abc /media/_torrent
fi

if [ ! -d /config/sonarr ]; then
  echo "Creating /config/sonarr"
  mkdir -p /config/sonarr
  chown -R abc:abc /config/sonarr
fi
